pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {

                git 'https://github.com/Aazain23/LAB-FAT.git'
            }
        }

        stage('Build') {
            steps {
 
                bat 'mvn clean install'
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}